micronaut:
  application:
    name: plexHookApi
  server:
    port: 8080
    multipart:
      enabled: true
    context-path: "/plex_hooks"
    thread-selection: auto
  metrics:
    enabled: true
    export:
      influx:
        enabled: false
        step: PT1M
        descriptions: false

endpoints:
  all:
    enabled: true
    sensitive: false

jackson:
  deserialization:
    fail-on-unknown-properties: false
  property-naming-strategy: SNAKE_CASE
  date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"

mongodb:
  uri: "mongodb://username:password@localhost:27017/?authSource=admin"
  db: "plexHooks"
  collection: "plexHooks"

plex:
  enabled-events:
    - PLAY
    - PAUSE
    - STOP
    - RESUME
    - LIBRARY_NEW_ITEM
  enabled-servers:
    - "plex-server"
  enable-all-users: true
  enabled-users:
    - "plex-user"
